---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: exampleSite/content/archives
  label: Archives
  create: all
  match: "**/*"
- type: directory
  path: exampleSite/content/blog
  label: Blog
  create: all
  match: "**/*"
- type: directory
  path: exampleSite/content/chapter1
  label: Chapter1
  create: all
  match: "**/*"
- type: directory
  path: exampleSite/content/chapter2
  label: Chapter2
  create: all
  match: "**/*"
- type: directory
  path: exampleSite/content/chapter3
  label: Chapter3
  create: all
  match: "**/*"
- type: directory
  path: exampleSite/content/chapter4
  label: Chapter4
  create: all
  match: "**/*"
- type: directory
  path: exampleSite/content/entry
  label: Entry
  create: all
  match: "**/*"
- type: directory
  path: exampleSite/content/getting-started
  label: Getting started
  create: all
  match: "**/*"
- type: directory
  path: exampleSite/content/post
  label: Post
  create: all
  match: "**/*"
- type: directory
  path: exampleSite/content/posts
  label: Posts
  create: all
  match: "**/*"
- type: directory
  path: exampleSite/content/sample
  label: Sample
  create: all
  match: "**/*"
- type: directory
  path: exampleSite/content
  label: Pages
  create: all
  match: "*"
upload_dir: exampleSite/static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.81.0
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --renderToDisk -d public
version: 0.81.0
