DefaultContentLanguage = "en"
baseURL = "https://example.com"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
enableMissingTranslationPlaceholders = false
hasCJKLanguage = true
languageCode = "en-us"
metaDataFormat = "yaml"
theme = "hugo-theme-techdoc"
title = "Hugo Techdoc Theme"
[markup]
defaultMarkdownHandler = "goldmark"
[markup.goldmark.renderer]
unsafe = true
[markup.tableOfContents]
endLevel = 6
ordered = false
startLevel = 2
[[menu.main]]
name = "Home"
url = "/"
weight = 1
[outputFormats.Algolia]
baseName = "algolia"
isPlainText = true
mediaType = "application/json"
notAlternative = true
[outputs]
home = ["HTML", "RSS", "Algolia"]
[params]
algolia_apiKey = "cbf12a63ff72d9c5dc0c10c195cf9128"
algolia_appId = "7W4SAN4PLK"
algolia_indexName = "hugo-demo-techdoc"
algolia_search_enable = true
custom_background_color = ""
custom_font_color = ""
dateformat = ""
description = "put your description"
github_doc_repository = "https://github.com/thingsym/hugo-theme-techdoc"
github_repository = "https://github.com/thingsym/hugo-theme-techdoc"
google_analytics_id = ""
google_site_verification = ""
images = ["images/og-image.png"]
menu_exclusion = ["archives", "archive", "blog", "entry", "post", "posts"]
menu_style = "open-menu"
tag_manager_container_id = ""
title = "Hugo Techdoc Theme"
version = "0.9.7"
[params.algolia]
params = ["tags", "categories"]
vars = ["title", "summary", "content", "date", "publishdate", "description", "permalink", "keywords", "lastmod"]
